In [2]:
import pandas as pd
auto = pd.read_csv('auto-mpg.data', sep=' ', na_values='?')

In [3]:
auto.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'car name']
head(auto)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
1,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
2,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
3,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
4,15.0,8,429.0,198.0,4341.0,10.0,70,1,ford galaxie 500
5,14.0,8,454.0,220.0,4354.0,9.0,70,1,chevrolet impala
6,14.0,8,440.0,215.0,4312.0,8.5,70,1,plymouth fury iii
7,14.0,8,455.0,225.0,4425.0,10.0,70,1,pontiac catalina
8,15.0,8,390.0,190.0,3850.0,8.5,70,1,amc ambassador dpl
9,15.0,8,383.0,170.0,3563.0,10.0,70,1,dodge challenger se
10,14.0,8,340.0,160.0,3609.0,8.0,70,1,plymouth 'cuda 340
11,15.0,8,400.0,150.0,3761.0,9.5,70,1,chevrolet monte carlo
12,14.0,8,455.0,225.0,3086.0,10.0,70,1,buick estate wagon (sw)
13,24.0,4,113.0,95.0,2372.0,15.0,70,3,toyota corona mark ii
14,22.0,6,198.0,95.0,2833.0,15.5,70,1,plymouth duster
15,18.0,6,199.0,97.0,2774.0,15.5,70,1,amc hornet
16,21.0,6,200.0,85.0,2587.0,16.0,70,1,ford maverick
17,27.0,4,97.0,88.0,2130.0,14.5,70,3,datsun pl510
18,26.0,4,97.0,46.0,1835.0,20.5,70,2,volkswagen 1131 deluxe sedan
19,25.0,4,110.0,87.0,2672.0,17.5,70,2,peugeot 504
20,24.0,4,107.0,90.0,2430.0,14.5,70,2,audi 100 ls
21,25.0,4,104.0,95.0,2375.0,17.5,70,2,saab 99e
22,26.0,4,121.0,113.0,2234.0,12.5,70,2,bmw 2002
23,21.0,6,199.0,90.0,2648.0,15.0,70,1,amc gremlin
24,10.0,8,360.0,215.0,4615.0,14.0,70,1,ford f250
25,10.0,8,307.0,200.0,4376.0,15.0,70,1,chevy c20
26,11.0,8,318.0,210.0,4382.0,13.5,70,1,dodge d200
27,9.0,8,304.0,193.0,4732.0,18.5,70,1,hi 1200d
28,27.0,4,97.0,88.0,2130.0,14.5,71,3,datsun pl510
29,28.0,4,140.0,90.0,2264.0,15.5,71,1,chevrolet vega 2300
...,...,...,...,...,...,...,...,...,...
367,27.0,4,112.0,88.0,2640.0,18.6,82,1,chevrolet cavalier wagon
368,34.0,4,112.0,88.0,2395.0,18.0,82,1,chevrolet cavalier 2-door
369,31.0,4,112.0,85.0,2575.0,16.2,82,1,pontiac j2000 se hatchback
370,29.0,4,135.0,84.0,2525.0,16.0,82,1,dodge aries se
371,27.0,4,151.0,90.0,2735.0,18.0,82,1,pontiac phoenix
372,24.0,4,140.0,92.0,2865.0,16.4,82,1,ford fairmont futura
373,23.0,4,151.0,NaN,3035.0,20.5,82,1,amc concord dl
374,36.0,4,105.0,74.0,1980.0,15.3,82,2,volkswagen rabbit l
375,37.0,4,91.0,68.0,2025.0,18.2,82,3,mazda glc custom l
376,31.0,4,91.0,68.0,1970.0,17.6,82,3,mazda glc custom
377,38.0,4,105.0,63.0,2125.0,14.7,82,1,plymouth horizon miser
378,36.0,4,98.0,70.0,2125.0,17.3,82,1,mercury lynx l
379,36.0,4,120.0,88.0,2160.0,14.5,82,3,nissan stanza xe
380,36.0,4,107.0,75.0,2205.0,14.5,82,3,honda accord
381,34.0,4,108.0,70.0,2245.0,16.9,82,3,toyota corolla
382,38.0,4,91.0,67.0,1965.0,15.0,82,3,honda civic
383,32.0,4,91.0,67.0,1965.0,15.7,82,3,honda civic (auto)
384,38.0,4,91.0,67.0,1995.0,16.2,82,3,datsun 310 gx
385,25.0,6,181.0,110.0,2945.0,16.4,82,1,buick century limited
386,38.0,6,262.0,85.0,3015.0,17.0,82,1,oldsmobile cutlass ciera (diesel)
387,26.0,4,156.0,92.0,2585.0,14.5,82,1,chrysler lebaron medallion
388,22.0,6,232.0,112.0,2835.0,14.7,82,1,ford granada l
389,32.0,4,144.0,96.0,2665.0,13.9,82,3,toyota celica gt
390,36.0,4,135.0,84.0,2370.0,13.0,82,1,dodge charger 2.2
391,27.0,4,151.0,90.0,2950.0,17.3,82,1,chevrolet camaro
392,27.0,4,140.0,86.0,2790.0,15.6,82,1,ford mustang gl
393,44.0,4,97.0,52.0,2130.0,24.6,82,2,vw pickup
394,32.0,4,135.0,84.0,2295.0,11.6,82,1,dodge rampage
395,28.0,4,120.0,79.0,2625.0,18.6,82,1,ford ranger
396,31.0,4,119.0,82.0,2720.0,19.4,82,1,chevy s-10

In [4]:
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [5]:
auto[auto.horsepower.isna()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
31,25.0,4,98.0,NaN,2046.0,19.0,71,1,ford pinto
125,21.0,6,200.0,NaN,2875.0,17.0,74,1,ford maverick
329,40.9,4,85.0,NaN,1835.0,17.3,80,2,renault lecar deluxe
335,23.6,4,140.0,NaN,2905.0,14.3,80,1,ford mustang cobra
353,34.5,4,100.0,NaN,2320.0,15.8,81,2,renault 18i
373,23.0,4,151.0,NaN,3035.0,20.5,82,1,amc concord dl

In [6]:
auto.horsepower.mean()

104.40409207161126

In [7]:
auto.horsepower.fillna(auto.horsepower.mean(), inplace=True)

In [8]:
auto.horsepower.isna().sum()

0

In [9]:
auto = pd.get_dummies(auto, columns=["cylinders"] )

In [10]:
auto = pd.get_dummies(auto, columns=["model year", "origin"] )
head(auto)

,mpg,displacement,horsepower,weight,acceleration,car name,cylinders_3,cylinders_4,cylinders_5,cylinders_6,...,model year_76,model year_77,model year_78,model year_79,model year_80,model year_81,model year_82,origin_1,origin_2,origin_3
0,15.0,350.0,165.000000,3693.0,11.5,buick skylark 320,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,18.0,318.0,150.000000,3436.0,11.0,plymouth satellite,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,16.0,304.0,150.000000,3433.0,12.0,amc rebel sst,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,17.0,302.0,140.000000,3449.0,10.5,ford torino,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,15.0,429.0,198.000000,4341.0,10.0,ford galaxie 500,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,14.0,454.0,220.000000,4354.0,9.0,chevrolet impala,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,14.0,440.0,215.000000,4312.0,8.5,plymouth fury iii,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,14.0,455.0,225.000000,4425.0,10.0,pontiac catalina,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,15.0,390.0,190.000000,3850.0,8.5,amc ambassador dpl,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9,15.0,383.0,170.000000,3563.0,10.0,dodge challenger se,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10,14.0,340.0,160.000000,3609.0,8.0,plymouth 'cuda 340,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,15.0,400.0,150.000000,3761.0,9.5,chevrolet monte carlo,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12,14.0,455.0,225.000000,3086.0,10.0,buick estate wagon (sw),0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13,24.0,113.0,95.000000,2372.0,15.0,toyota corona mark ii,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
14,22.0,198.0,95.000000,2833.0,15.5,plymouth duster,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
15,18.0,199.0,97.000000,2774.0,15.5,amc hornet,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
16,21.0,200.0,85.000000,2587.0,16.0,ford maverick,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
17,27.0,97.0,88.000000,2130.0,14.5,datsun pl510,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
18,26.0,97.0,46.000000,1835.0,20.5,volkswagen 1131 deluxe sedan,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
19,25.0,110.0,87.000000,2672.0,17.5,peugeot 504,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
20,24.0,107.0,90.000000,2430.0,14.5,audi 100 ls,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
21,25.0,104.0,95.000000,2375.0,17.5,saab 99e,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
22,26.0,121.0,113.000000,2234.0,12.5,bmw 2002,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
23,21.0,199.0,90.000000,2648.0,15.0,amc gremlin,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
24,10.0,360.0,215.000000,4615.0,14.0,ford f250,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
25,10.0,307.0,200.000000,4376.0,15.0,chevy c20,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
26,11.0,318.0,210.000000,4382.0,13.5,dodge d200,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
27,9.0,304.0,193.000000,4732.0,18.5,hi 1200d,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,27.0,97.0,88.000000,2130.0,14.5,datsun pl510,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
29,28.0,140.0,90.000000,2264.0,15.5,chevrolet vega 2300,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,27.0,112.0,88.000000,2640.0,18.6,chevrolet cavalier wagon,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
368,34.0,112.0,88.000000,2395.0,18.0,chevrolet cavalier 2-door,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
369,31.0,112.0,85.000000,2575.0,16.2,pontiac j2000 se hatchback,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
370,29.0,135.0,84.000000,2525.0,16.0,dodge aries se,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
371,27.0,151.0,90.000000,2735.0,18.0,pontiac phoenix,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
372,24.0,140.0,92.000000,2865.0,16.4,ford fairmont futura,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
373,23.0,151.0,104.404092,3035.0,20.5,amc concord dl,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
374,36.0,105.0,74.000000,1980.0,15.3,volkswagen rabbit l,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
375,37.0,91.0,68.000000,2025.0,18.2,mazda glc custom l,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
376,31.0,91.0,68.000000,1970.0,17.6,mazda glc custom,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
377,38.0,105.0,63.000000,2125.0,14.7,plymouth horizon miser,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
378,36.0,98.0,70.000000,2125.0,17.3,mercury lynx l,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
379,36.0,120.0,88.000000,2160.0,14.5,nissan stanza xe,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
380,36.0,107.0,75.000000,2205.0,14.5,honda accord,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
381,34.0,108.0,70.000000,2245.0,16.9,toyota corolla,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
382,38.0,91.0,67.000000,1965.0,15.0,honda civic,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
383,32.0,91.0,67.000000,1965.0,15.7,honda civic (auto),0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
384,38.0,91.0,67.000000,1995.0,16.2,datsun 310 gx,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
385,25.0,181.0,110.000000,2945.0,16.4,buick century limited,0,0,0,1,...,0,0,0,0,0,0,1,1,0,0
386,38.0,262.0,85.000000,3015.0,17.0,oldsmobile cutlass ciera (diesel),0,0,0,1,...,0,0,0,0,0,0,1,1,0,0
387,26.0,156.0,92.000000,2585.0,14.5,chrysler lebaron medallion,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
388,22.0,232.0,112.000000,2835.0,14.7,ford granada l,0,0,0,1,...,0,0,0,0,0,0,1,1,0,0
389,32.0,144.0,96.000000,2665.0,13.9,toyota celica gt,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
390,36.0,135.0,84.000000,2370.0,13.0,dodge charger 2.2,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
391,27.0,151.0,90.000000,2950.0,17.3,chevrolet camaro,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
392,27.0,140.0,86.000000,2790.0,15.6,ford mustang gl,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
393,44.0,97.0,52.000000,2130.0,24.6,vw pickup,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
394,32.0,135.0,84.000000,2295.0,11.6,dodge rampage,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
395,28.0,120.0,79.000000,2625.0,18.6,ford ranger,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
396,31.0,119.0,82.000000,2720.0,19.4,chevy s-10,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0

In [11]:
from sklearn import datasets

/home/ni2633244/anaconda3/lib/python3.5/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression()

In [14]:
y = auto.mpg

In [15]:
auto.drop(columns = ["mpg", "car name"], inplace = True)

In [16]:
head(auto)

,displacement,horsepower,weight,acceleration,cylinders_3,cylinders_4,cylinders_5,cylinders_6,cylinders_8,model year_70,...,model year_76,model year_77,model year_78,model year_79,model year_80,model year_81,model year_82,origin_1,origin_2,origin_3
0,350.0,165.000000,3693.0,11.5,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
1,318.0,150.000000,3436.0,11.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
2,304.0,150.000000,3433.0,12.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
3,302.0,140.000000,3449.0,10.5,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
4,429.0,198.000000,4341.0,10.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
5,454.0,220.000000,4354.0,9.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
6,440.0,215.000000,4312.0,8.5,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
7,455.0,225.000000,4425.0,10.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
8,390.0,190.000000,3850.0,8.5,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
9,383.0,170.000000,3563.0,10.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
10,340.0,160.000000,3609.0,8.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
11,400.0,150.000000,3761.0,9.5,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
12,455.0,225.000000,3086.0,10.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
13,113.0,95.000000,2372.0,15.0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
14,198.0,95.000000,2833.0,15.5,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
15,199.0,97.000000,2774.0,15.5,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
16,200.0,85.000000,2587.0,16.0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
17,97.0,88.000000,2130.0,14.5,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
18,97.0,46.000000,1835.0,20.5,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
19,110.0,87.000000,2672.0,17.5,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
20,107.0,90.000000,2430.0,14.5,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
21,104.0,95.000000,2375.0,17.5,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
22,121.0,113.000000,2234.0,12.5,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
23,199.0,90.000000,2648.0,15.0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
24,360.0,215.000000,4615.0,14.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
25,307.0,200.000000,4376.0,15.0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
26,318.0,210.000000,4382.0,13.5,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
27,304.0,193.000000,4732.0,18.5,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
28,97.0,88.000000,2130.0,14.5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
29,140.0,90.000000,2264.0,15.5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,112.0,88.000000,2640.0,18.6,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
368,112.0,88.000000,2395.0,18.0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
369,112.0,85.000000,2575.0,16.2,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
370,135.0,84.000000,2525.0,16.0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
371,151.0,90.000000,2735.0,18.0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
372,140.0,92.000000,2865.0,16.4,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
373,151.0,104.404092,3035.0,20.5,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
374,105.0,74.000000,1980.0,15.3,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
375,91.0,68.000000,2025.0,18.2,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
376,91.0,68.000000,1970.0,17.6,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
377,105.0,63.000000,2125.0,14.7,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
378,98.0,70.000000,2125.0,17.3,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
379,120.0,88.000000,2160.0,14.5,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
380,107.0,75.000000,2205.0,14.5,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
381,108.0,70.000000,2245.0,16.9,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
382,91.0,67.000000,1965.0,15.0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
383,91.0,67.000000,1965.0,15.7,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
384,91.0,67.000000,1995.0,16.2,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
385,181.0,110.000000,2945.0,16.4,0,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
386,262.0,85.000000,3015.0,17.0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
387,156.0,92.000000,2585.0,14.5,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
388,232.0,112.000000,2835.0,14.7,0,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
389,144.0,96.000000,2665.0,13.9,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
390,135.0,84.000000,2370.0,13.0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
391,151.0,90.000000,2950.0,17.3,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
392,140.0,86.000000,2790.0,15.6,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
393,97.0,52.000000,2130.0,24.6,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
394,135.0,84.000000,2295.0,11.6,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
395,120.0,79.000000,2625.0,18.6,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
396,119.0,82.000000,2720.0,19.4,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(auto, y, test_size=0.33, random_state=42)

In [19]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [20]:
y_pred

array([ 13.81971318,  31.07566536,  28.14096894,  25.46637403,
        14.82975548,  33.68174379,  13.3149288 ,  12.45158781,
        18.04142379,  27.64847871,  16.20993026,  25.69753342,
        28.61010452,  21.46825875,  29.92650872,  27.9525697 ,
        11.21368687,  21.30048187,  22.81685412,  29.94647537,
        20.19333892,  22.27075161,  31.80738729,  15.71192556,
         9.9062421 ,  26.69783805,  27.01947992,  17.43956954,
        24.72949823,  21.04713017,  12.34594165,  29.69248374,
        37.02382644,  26.1192455 ,  22.31018295,  38.28100782,
        20.51294122,  19.32169075,  35.65126754,  24.6516968 ,
        10.58269041,  32.38069739,  27.76805102,  25.13394885,
        25.9708223 ,  25.15790373,   6.10037437,  18.47373237,
        34.25261398,  25.38431355,  33.06990947,  14.74891214,
        19.25510121,  11.82985985,  27.63175222,  21.01075641,
        30.77523583,  14.65576136,  23.37662081,  11.85068168,
        25.44855221,  25.81897674,  25.98137881,  23.84176674,
        24.80448783,  26.75686504,  31.20759509,  28.89220018,
        22.99412883,  27.2382959 ,  10.17835669,  25.59819496,
        35.54038622,  31.48554941,  16.46738805,  29.47062985,
        25.83142892,  15.69876923,  18.06189235,  30.05152971,
        16.63700121,  25.33259683,  24.03955914,  13.75992773,
        32.3836893 ,   7.59565155,  34.5676637 ,  19.19892613,
        30.5668931 ,  27.51627846,  28.92695217,  31.12477025,
        28.53162392,  34.57289394,  30.24179352,  19.5172318 ,
        21.17368292,  21.63088188,  30.92498294,  23.93506426,
        21.62751763,   8.88094247,  33.87975153,   9.5540931 ,
        24.27147739,  17.77539437,  33.24071795,  35.01044915,
        22.31091066,  26.60598923,  22.53273768,  35.71073986,
        30.55687333,  24.7492241 ,  23.95751463,  21.5088609 ,
        35.24785058,  22.51083315,  39.11746955,  25.14598066,
        27.58030456,  19.49111085,   8.8241631 ,  19.99028965,
        29.84658861,  24.67516314,  13.13677027,  38.67221919,
        30.62719205,  10.91848778,  22.07572981,  29.30749176])

In [21]:
from sklearn.metrics import mean_squared_error, r2_score

In [22]:
mean_squared_error(y_test, y_pred)

9.0126938546533388

In [23]:
from sklearn.linear_model import SGDRegressor

In [24]:
model2 = SGDRegressor(penalty='l2', alpha=1, max_iter=10000, early_stopping=True, eta0=0.0000001)
model2.fit(X_train, y_train)

SGDRegressor(alpha=1, average=False, early_stopping=True, epsilon=0.1,
       eta0=1e-07, fit_intercept=True, l1_ratio=0.15,
       learning_rate='invscaling', loss='squared_loss', max_iter=10000,
       n_iter=None, n_iter_no_change=5, penalty='l2', power_t=0.25,
       random_state=None, shuffle=True, tol=None, validation_fraction=0.1,
       verbose=0, warm_start=False)

In [25]:
model2.predict(X_test)

array([ 12.99785561,  23.5162132 ,  24.53602314,  25.15140498,
        19.35867307,  23.35331118,  24.69121057,  25.53444423,
        14.55894374,  32.87124468,   2.54931128,  13.75847696,
        19.16650187,  34.5124008 ,  29.09256717,  23.13387298,
        15.93287971,  32.12360985,  17.41671472,  22.05344466,
        17.18272159,  15.7049465 ,  30.78905585,  10.04961423,
        22.25847011,  26.54365651,  25.03393495,  22.50379755,
        24.50138841,   8.7853211 ,  17.22578351,  28.55686209,
        24.58644805,  26.05135549,  34.06319598,  22.71304978,
        12.39516912,  24.99246293,  26.12198104,  22.31639324,
        32.64581162,  24.0334091 ,  23.42540644,  24.74449387,
        27.79568681,  25.73726873,  15.67508061,  14.99090198,
        27.41714938,  25.1607413 ,  19.1435695 ,  14.96304798,
        13.55403726,   9.43601459,  25.06244021,  14.60179608,
        18.37301803,   9.91256413,  24.69758308,  21.14195874,
        25.73874915,  27.62945894,   7.57153921,  29.15380807,
        26.00161728,  25.33828929,  26.32715432,  26.86534445,
        33.37725394,  26.6219033 ,   6.65727786,  20.51199008,
        22.688862  ,  27.41893375,  19.83292949,  30.60579922,
        22.43492099,  22.19595759,  12.04997518,  17.49990249,
        29.00761926,  27.96784225,  31.23322045,  20.38592401,
        23.61915242,  14.17273811,  23.16696882,  21.77258375,
        27.41518805,  23.98126567,  23.46917003,  23.23922687,
        26.81668736,  22.86776033,  23.99801137,  22.06953724,
        16.51200596,  35.5327531 ,  35.93534871,  20.51705922,
        12.96407604,  13.88311998,  22.02349032,   8.31090363,
        31.31485998,  18.44132764,  23.26790028,  23.92191104,
        30.77916332,  28.48656322,  19.5714964 ,  22.17664791,
        30.0555381 ,  22.68883113,  24.88498276,  22.32276894,
        23.64559434,  18.06690119,  20.15957799,  28.42245646,
        25.85148703,  13.50531895,  27.91239986,  13.32947888,
        28.00058762,  15.193662  ,  24.76969208,  23.71517244,
        29.20482724,  14.76435863,  28.69945106,  25.24874935])

In [26]:
model2.coef_

array([-0.18433608,  0.132765  ,  0.01360988,  0.2078355 , -0.00058294,
        0.02239578, -0.0004083 , -0.00283514, -0.00535075,  0.00060346,
        0.00172858, -0.00160329, -0.00185088, -0.00021593, -0.00130427,
       -0.00141091, -0.00038927,  0.00046184,  0.00343627,  0.0059961 ,
        0.00372675,  0.00404021,  0.0010997 ,  0.00228278,  0.00983617])

In [27]:
y_pred = model2.predict(X_test)
mean_squared_error(y_test, y_pred)

68.526938901759976

In [28]:
y_pred

array([ 12.99785561,  23.5162132 ,  24.53602314,  25.15140498,
        19.35867307,  23.35331118,  24.69121057,  25.53444423,
        14.55894374,  32.87124468,   2.54931128,  13.75847696,
        19.16650187,  34.5124008 ,  29.09256717,  23.13387298,
        15.93287971,  32.12360985,  17.41671472,  22.05344466,
        17.18272159,  15.7049465 ,  30.78905585,  10.04961423,
        22.25847011,  26.54365651,  25.03393495,  22.50379755,
        24.50138841,   8.7853211 ,  17.22578351,  28.55686209,
        24.58644805,  26.05135549,  34.06319598,  22.71304978,
        12.39516912,  24.99246293,  26.12198104,  22.31639324,
        32.64581162,  24.0334091 ,  23.42540644,  24.74449387,
        27.79568681,  25.73726873,  15.67508061,  14.99090198,
        27.41714938,  25.1607413 ,  19.1435695 ,  14.96304798,
        13.55403726,   9.43601459,  25.06244021,  14.60179608,
        18.37301803,   9.91256413,  24.69758308,  21.14195874,
        25.73874915,  27.62945894,   7.57153921,  29.15380807,
        26.00161728,  25.33828929,  26.32715432,  26.86534445,
        33.37725394,  26.6219033 ,   6.65727786,  20.51199008,
        22.688862  ,  27.41893375,  19.83292949,  30.60579922,
        22.43492099,  22.19595759,  12.04997518,  17.49990249,
        29.00761926,  27.96784225,  31.23322045,  20.38592401,
        23.61915242,  14.17273811,  23.16696882,  21.77258375,
        27.41518805,  23.98126567,  23.46917003,  23.23922687,
        26.81668736,  22.86776033,  23.99801137,  22.06953724,
        16.51200596,  35.5327531 ,  35.93534871,  20.51705922,
        12.96407604,  13.88311998,  22.02349032,   8.31090363,
        31.31485998,  18.44132764,  23.26790028,  23.92191104,
        30.77916332,  28.48656322,  19.5714964 ,  22.17664791,
        30.0555381 ,  22.68883113,  24.88498276,  22.32276894,
        23.64559434,  18.06690119,  20.15957799,  28.42245646,
        25.85148703,  13.50531895,  27.91239986,  13.32947888,
        28.00058762,  15.193662  ,  24.76969208,  23.71517244,
        29.20482724,  14.76435863,  28.69945106,  25.24874935])

In [29]:
from sklearn.model_selection import GridSearchCV

In [30]:
parameters = {'penalty': ['l1', 'l2'], 'alpha': [0.01, 0.1, 0.5, 1], 'max_iter': [1000, 5000, 10000]}

In [37]:
model3 = SGDRegressor(early_stopping=True, eta0=0.0000001)

In [38]:
gs_model = GridSearchCV(model3, parameters, scoring='neg_mean_squared_error', cv=5, n_jobs=-1)

In [39]:
gs_model.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=SGDRegressor(alpha=0.0001, average=False, early_stopping=True, epsilon=0.1,
       eta0=1e-07, fit_intercept=True, l1_ratio=0.15,
       learning_rate='invscaling', loss='squared_loss', max_iter=None,
       n_iter=None, n_iter_no_change=5, penalty='l2', power_t=0.25,
       random_state=None, shuffle=True, tol=None, validation_fraction=0.1,
       verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'penalty': ['l1', 'l2'], 'alpha': [0.01, 0.1, 0.5, 1], 'max_iter': [1000, 5000, 10000]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_squared_error', verbose=0)

In [40]:
gs_model.best_params_

{'alpha': 0.01, 'max_iter': 10000, 'penalty': 'l1'}

In [41]:
gs_model.best_estimator_

SGDRegressor(alpha=0.01, average=False, early_stopping=True, epsilon=0.1,
       eta0=1e-07, fit_intercept=True, l1_ratio=0.15,
       learning_rate='invscaling', loss='squared_loss', max_iter=10000,
       n_iter=None, n_iter_no_change=5, penalty='l1', power_t=0.25,
       random_state=None, shuffle=True, tol=None, validation_fraction=0.1,
       verbose=0, warm_start=False)

In [42]:
gs_model.best_score_

-79.364484641864209